import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
    title: "Privacy Policy",
    description: "Privacy Policy for SYS.VISUAL_INTEL. Learn how we handle your data and protect your privacy.",
};

export default function PrivacyPage() {
    return (
        <div className="min-h-screen bg-black text-white">
            {/* Header */}
            <header className="border-b border-stone-800 bg-black/50 backdrop-blur-sm sticky top-0 z-50">
                <div className="max-w-4xl mx-auto px-6 py-4 flex justify-between items-center">
                    <Link href="/" className="text-xl font-bold tracking-tight">
                        SYS.VISUAL_INTEL
                    </Link>
                    <Link
                        href="/"
                        className="text-sm text-stone-400 hover:text-emerald-400 transition-colors"
                    >
                        ← Back to Tool
                    </Link>
                </div>
            </header>

            {/* Content */}
            <main className="max-w-4xl mx-auto px-6 py-12">
                <h1 className="text-4xl font-bold mb-4">Privacy Policy</h1>
                <p className="text-stone-400 mb-8">Last Updated: January 31, 2026</p>

                <div className="space-y-8 text-stone-300 leading-relaxed">
                    <section>
                        <h2 className="text-2xl font-semibold text-white mb-4">1. Introduction</h2>
                        <p>
                            SYS.VISUAL_INTEL ("we," "our," or "the Service") is committed to protecting your privacy. This Privacy
                            Policy explains how we collect, use, process, and safeguard information when you use our geolocation
                            analysis service.
                        </p>
                    </section>

                    <section className="bg-emerald-900/20 border border-emerald-800 rounded-lg p-6">
                        <h2 className="text-2xl font-semibold text-emerald-400 mb-4">2. Data We Collect</h2>

                        <h3 className="text-lg font-semibold text-white mb-3 mt-4">2.1 Images You Upload</h3>
                        <p className="mb-3">
                            When you use the Service, you upload images for geolocation analysis. These images are:
                        </p>
                        <ul className="space-y-2 list-disc list-inside mb-4">
                            <li>Processed in real-time by our AI analysis system</li>
                            <li>Temporarily stored in memory during processing</li>
                            <li>Not permanently saved to our servers after analysis is complete</li>
                            <li>Automatically deleted after processing</li>
                        </ul>

                        <h3 className="text-lg font-semibold text-white mb-3 mt-4">2.2 Analysis Results</h3>
                        <p className="mb-3">
                            The geolocation analysis results generated by the Service, including estimated locations, confidence
                            scores, and visual analysis data, are displayed to you but are not stored long-term.
                        </p>

                        <h3 className="text-lg font-semibold text-white mb-3 mt-4">2.3 Technical Information</h3>
                        <p className="mb-3">We may collect standard technical information including:</p>
                        <ul className="space-y-2 list-disc list-inside">
                            <li>Browser type and version</li>
                            <li>Operating system</li>
                            <li>IP address (for security and abuse prevention)</li>
                            <li>Access times and dates</li>
                            <li>Pages visited and features used</li>
                        </ul>
                    </section>

                    <section>
                        <h2 className="text-2xl font-semibold text-white mb-4">3. How We Use Your Information</h2>
                        <p className="mb-3">We use collected information for the following purposes:</p>
                        <ul className="space-y-2 list-disc list-inside">
                            <li>To provide and operate the geolocation analysis service</li>
                            <li>To improve and optimize the Service's performance and accuracy</li>
                            <li>To detect, prevent, and address technical issues and security threats</li>
                            <li>To enforce our Terms of Service and Acceptable Use Policy</li>
                            <li>To comply with legal obligations and respond to lawful requests</li>
                        </ul>
                    </section>

                    <section className="bg-amber-900/20 border border-amber-800 rounded-lg p-6">
                        <h2 className="text-2xl font-semibold text-amber-400 mb-4">4. Content Moderation and Safety</h2>
                        <p className="mb-3">
                            To maintain a safe and legal service, we employ automated content moderation systems that:
                        </p>
                        <ul className="space-y-2 list-disc list-inside">
                            <li>Scan uploaded images for prohibited content (including sexually explicit material)</li>
                            <li>Flag potential violations of our Terms of Service</li>
                            <li>Block processing of images that violate our policies</li>
                            <li>Log violations for security and legal compliance purposes</li>
                        </ul>
                        <p className="mt-3 font-semibold text-amber-300">
                            Images flagged as containing prohibited content may be retained temporarily for review and reporting
                            to authorities as required by law.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-semibold text-white mb-4">5. Data Sharing and Disclosure</h2>
                        <p className="mb-3">We do not sell, trade, or rent your personal information. We may share data only in the following circumstances:</p>

                        <h3 className="text-lg font-semibold text-white mb-3 mt-4">5.1 Service Providers</h3>
                        <p className="mb-3">
                            We use third-party AI services (Google Gemini) to process images and generate geolocation analysis.
                            These providers process data according to their own privacy policies and security standards.
                        </p>

                        <h3 className="text-lg font-semibold text-white mb-3 mt-4">5.2 Legal Requirements</h3>
                        <p className="mb-3">We may disclose information when required by law or to:</p>
                        <ul className="space-y-2 list-disc list-inside">
                            <li>Comply with legal processes or government requests</li>
                            <li>Enforce our Terms of Service</li>
                            <li>Protect the rights, property, or safety of our users or the public</li>
                            <li>Report illegal content (such as child exploitation material) to authorities</li>
                        </ul>
                    </section>

                    <section>
                        <h2 className="text-2xl font-semibold text-white mb-4">6. Data Security</h2>
                        <p className="mb-3">
                            We implement industry-standard security measures to protect your data, including:
                        </p>
                        <ul className="space-y-2 list-disc list-inside">
                            <li>Encrypted data transmission (HTTPS/TLS)</li>
                            <li>Secure server infrastructure</li>
                            <li>Access controls and authentication</li>
                            <li>Regular security audits and updates</li>
                            <li>Automated threat detection and prevention</li>
                        </ul>
                        <p className="mt-3">
                            However, no method of transmission over the internet is 100% secure. While we strive to protect your
                            information, we cannot guarantee absolute security.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-semibold text-white mb-4">7. Data Retention</h2>
                        <p className="mb-3">
                            <strong>Uploaded Images:</strong> Deleted immediately after analysis is complete (typically within seconds)
                        </p>
                        <p className="mb-3">
                            <strong>Analysis Results:</strong> Not stored long-term; available only during your active session
                        </p>
                        <p className="mb-3">
                            <strong>Technical Logs:</strong> Retained for up to 90 days for security and operational purposes
                        </p>
                        <p className="mb-3">
                            <strong>Violation Records:</strong> Retained as necessary for legal compliance and enforcement
                        </p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-semibold text-white mb-4">8. Cookies and Tracking</h2>
                        <p>
                            The Service uses minimal cookies and tracking technologies for essential functionality. We do not use
                            third-party advertising cookies or tracking for marketing purposes.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-semibold text-white mb-4">9. Your Rights</h2>
                        <p className="mb-3">Depending on your jurisdiction, you may have the following rights:</p>
                        <ul className="space-y-2 list-disc list-inside">
                            <li>Right to access information we hold about you</li>
                            <li>Right to request deletion of your data</li>
                            <li>Right to object to processing of your data</li>
                            <li>Right to data portability</li>
                            <li>Right to withdraw consent</li>
                        </ul>
                        <p className="mt-3">
                            To exercise these rights, please contact us through the Service interface.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-semibold text-white mb-4">10. Children's Privacy</h2>
                        <p>
                            The Service is not intended for use by individuals under the age of 18. We do not knowingly collect
                            personal information from children. If we become aware that we have collected data from a child without
                            parental consent, we will take steps to delete that information.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-semibold text-white mb-4">11. International Data Transfers</h2>
                        <p>
                            Your information may be processed in countries other than your own. By using the Service, you consent
                            to the transfer of your information to countries that may have different data protection laws than
                            your jurisdiction.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-semibold text-white mb-4">12. Changes to This Privacy Policy</h2>
                        <p>
                            We may update this Privacy Policy from time to time. Material changes will be communicated through the
                            Service interface. Continued use of the Service after changes constitutes acceptance of the updated policy.
                        </p>
                    </section>

                    <section className="bg-stone-900/50 border border-stone-800 rounded-lg p-6">
                        <h2 className="text-2xl font-semibold text-white mb-4">13. Contact Us</h2>
                        <p className="mb-3">
                            If you have questions about this Privacy Policy or our data practices, please review our{" "}
                            <Link href="/terms" className="text-emerald-400 hover:underline">
                                Terms of Service
                            </Link>
                            {" "}and{" "}
                            <Link href="/acceptable-use" className="text-emerald-400 hover:underline">
                                Acceptable Use Policy
                            </Link>
                            {" "}for additional information.
                        </p>
                    </section>

                    <div className="pt-8 border-t border-stone-800">
                        <p className="text-sm text-stone-500">
                            By using SYS.VISUAL_INTEL, you acknowledge that you have read and understood this Privacy Policy.
                        </p>
                    </div>
                </div>
            </main>

            {/* Footer */}
            <footer className="border-t border-stone-800 mt-16 py-8">
                <div className="max-w-4xl mx-auto px-6">
                    <div className="flex flex-wrap gap-6 justify-center text-sm text-stone-400 mb-4">
                        <Link href="/terms" className="hover:text-emerald-400 transition-colors">
                            Terms of Service
                        </Link>
                        <Link href="/privacy" className="hover:text-emerald-400 transition-colors">
                            Privacy Policy
                        </Link>
                        <Link href="/acceptable-use" className="hover:text-emerald-400 transition-colors">
                            Acceptable Use
                        </Link>
                    </div>
                    <p className="text-center text-stone-500 text-sm">
                        © 2026 SYS.VISUAL_INTEL. All rights reserved.
                    </p>
                </div>
            </footer>
        </div>
    );
}
